image: node:16

definitions:
  steps:
    - step: &deploy
        name: deploy
        script:
          # setup
          - echo -e "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_REGION
          - export AWS_REGION=$AWS_REGION
          - export STAGE=$BITBUCKET_BRANCH
          - npm -g i npm
          # install layer dependencies
          - cd $BITBUCKET_CLONE_DIR/src/layers/vincelive-internal/nodejs
          # use latest versions instead of version in package-lock.json
          - npm i
          - npm list
          # install root
          - cd $BITBUCKET_CLONE_DIR/
          - npm ci
          - npm install -g aws-cdk
          - cdk deploy "*" --require-approval=never
          # update lambdas
          - node ci-scripts/update-lambdas.js

pipelines:
  branches:
    dev:
      - step:
          <<: *deploy
          name: Deploy to dev
          deployment: dev
    staging:
      - step:
          <<: *deploy
          name: Deploy to staging
          deployment: staging
    prod:
      - step:
          <<: *deploy
          name: Deploy to prod
          deployment: prod
