image: node:14

definitions:
  caches:
    python3: /usr/bin/python3.9
  steps:
    - step: &deploy
        name: deploy
        caches:
          - python3
        script:
          # process
          - echo -e "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_REGION
          - export STAGE=$BITBUCKET_BRANCH
          - npm -g i npm
          - npm install @mapbox/node-pre-gyp -g
          - cd $BITBUCKET_CLONE_DIR/src/layers/vincelive-internal/nodejs
          - npm ci
          - cd $BITBUCKET_CLONE_DIR/
          - npm ci
          - npm install -g aws-cdk@^1.134.0
          - cdk deploy "*" --require-approval=never
pipelines:
  branches:
    dev:
      - step:
          <<: *deploy
          name: Deploy to dev
          deployment: dev
    staging:
      - step:
          <<: *deploy
          name: Deploy to staging
          deployment: staging
    prod:
      - step:
          <<: *deploy
          name: Deploy to prod
          deployment: prod
