image: node:14

definitions:
  steps:
    - step: &deploy
        name: deploy
        script:
          # process
          - apt-get update
          - apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev
          - curl -O https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tar.xz
          - tar -xf Python-3.8.2.tar.xz
          - cd Python-3.8.2
          - ./configure --enable-optimizations
          - make -j 4
          - make altinstall
          - python3.8 --version
          - cat /etc/os-release
          - echo -e "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_REGION
          - export STAGE=$BITBUCKET_BRANCH
          - npm -g i npm
          - cd $BITBUCKET_CLONE_DIR/src/layers/vincelive-internal/nodejs
          - npm ci
          - cd $BITBUCKET_CLONE_DIR/src/layers/sqlite-layer/nodejs
          - npm ci
          - cd $BITBUCKET_CLONE_DIR/
          - npm ci
          - npm install -g aws-cdk@^1.134.0
          - cdk deploy "*" --require-approval=never
pipelines:
  branches:
    dev:
      - step:
          <<: *deploy
          name: Deploy to dev
          deployment: dev
    staging:
      - step:
          <<: *deploy
          name: Deploy to staging
          deployment: staging
    prod:
      - step:
          <<: *deploy
          name: Deploy to prod
          deployment: prod
